// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgk8YDUtzNANc-sjnmulTyuOwO4GAJ_oo',
    appId: '1:245710505013:web:6c7d71a6e4dcba47d69d7c',
    messagingSenderId: '245710505013',
    projectId: 'flutterappmobil',
    authDomain: 'flutterappmobil.firebaseapp.com',
    storageBucket: 'flutterappmobil.appspot.com',
    measurementId: 'G-EPN2FGT935',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfdKEfpJTr7aSC-YuUGWvAcjFvd4TD1ZI',
    appId: '1:245710505013:android:2c47448b8fed402ad69d7c',
    messagingSenderId: '245710505013',
    projectId: 'flutterappmobil',
    storageBucket: 'flutterappmobil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARZYmEE355Cce21K6VXO9dBZqUCXPuFL4',
    appId: '1:245710505013:ios:8e7e1141f36cdb87d69d7c',
    messagingSenderId: '245710505013',
    projectId: 'flutterappmobil',
    storageBucket: 'flutterappmobil.appspot.com',
    iosClientId: '245710505013-li5u7o4mjomsuc52os4bq9e09afgl1vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARZYmEE355Cce21K6VXO9dBZqUCXPuFL4',
    appId: '1:245710505013:ios:8e7e1141f36cdb87d69d7c',
    messagingSenderId: '245710505013',
    projectId: 'flutterappmobil',
    storageBucket: 'flutterappmobil.appspot.com',
    iosClientId: '245710505013-li5u7o4mjomsuc52os4bq9e09afgl1vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
